In [1]:
import pandas as pd
file_path=r"C:\Users\HP\OneDrive\เอกสาร\remote-connectivity\data\raw\mobile-coverage-all-sites.xlsx"
df = pd.read_excel(file_path, skiprows=4)

df.head()

,SITE NAME,SITE TYPE,POPULATION,MACRO CELL,SMALL CELL,PROXIMITY TO CELL,PROVIDER,LATITUDE,LONGITUDE
0,ADELAIDE RIVER,VILLAGE,317.0,YES,NaN,NaN,OPTUS/TELSTRA,-13.23780,131.10473
1,AILERON STATION,HIGHWAY,NaN,NaN,NaN,YES,OPTUS/TELSTRA,-22.50000,133.24500
2,ALAMIRRA,COMMUNITY,5.0,NaN,NaN,YES,TELSTRA,-11.06700,132.52800
3,ALI CURUNG,COMMUNITY,394.0,YES,NaN,NaN,TELSTRA,-21.00333,134.40694
4,ALPURRURULAM,COMMUNITY,350.0,YES,NaN,NaN,TELSTRA,-20.98417,137.84749

In [2]:
df.shape

(188, 9)

In [3]:
df.columns

Index(['SITE NAME', 'SITE TYPE', 'POPULATION', 'MACRO CELL', 'SMALL CELL',
       'PROXIMITY TO CELL', 'PROVIDER', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SITE NAME          188 non-null    object
 1   SITE TYPE          188 non-null    object
 2   POPULATION         155 non-null    float64
 3   MACRO CELL         62 non-null     object
 4   SMALL CELL         35 non-null     object
 5   PROXIMITY TO CELL  98 non-null     object
 6   PROVIDER           188 non-null    object
 7   LATITUDE           188 non-null    float64
 8   LONGITUDE          188 non-null    float64
dtypes: float64(3), object(6)
memory usage: 13.3+ KB

In [5]:
df.isnull().sum()

SITE NAME              0
SITE TYPE              0
POPULATION            33
MACRO CELL           126
SMALL CELL           153
PROXIMITY TO CELL     90
PROVIDER               0
LATITUDE               0
LONGITUDE              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["MACRO CELL"].value_counts(dropna=False)

MACRO CELL
NaN    126
YES     62
Name: count, dtype: int64

In [8]:
df["SMALL CELL"].value_counts(dropna=False)

SMALL CELL
NaN    153
YES     35
Name: count, dtype: int64

In [9]:
df["PROXIMITY TO CELL"].value_counts(dropna=False)

PROXIMITY TO CELL
YES    98
NaN    90
Name: count, dtype: int64

In [10]:
df["SITE TYPE"].value_counts(dropna=False)

SITE TYPE
COMMUNITY    148
HIGHWAY       17
TOURISM       15
VILLAGE        8
Name: count, dtype: int64

In [11]:
df[df["POPULATION"].isna()][
    ["SITE NAME", "SITE TYPE", "PROVIDER", "LATITUDE", "LONGITUDE"]
]

                     SITE NAME SITE TYPE       PROVIDER  LATITUDE  LONGITUDE
1              AILERON STATION   HIGHWAY  OPTUS/TELSTRA -22.50000  133.24500
14               AURORA KAKADU   TOURISM          OPTUS -12.67600  132.48000
17                BARROW CREEK   HIGHWAY  OPTUS/TELSTRA -21.53100  133.88900
29               COOINDA LODGE   TOURISM        TELSTRA -12.90500  132.52200
30   CURTAIN SPRINGS ROADHOUSE   HIGHWAY  OPTUS/TELSTRA -25.31400  131.75600
32                 DALY WATERS   VILLAGE  OPTUS/TELSTRA -16.25333  133.36932
33        DEVILS MARBLES HOTEL   TOURISM          OPTUS -20.64100  134.22300
39          DUNMARRA ROADHOUSE   HIGHWAY  OPTUS/TELSTRA -16.67900  133.41200
44                    ERLDUNDA   HIGHWAY  OPTUS/TELSTRA -25.19700  133.20000
46              FLORENCE FALLS   TOURISM          OPTUS -13.10900  130.79300
52               GEM TREE PARK   TOURISM          OPTUS -22.96800  134.24300
53        GLEN HELEN HOMESTEAD   TOURISM          OPTUS -23.68500  132.67200
75         KINGS CANYON RESORT   TOURISM  OPTUS/TELSTRA -24.24800  131.51200
76         KINGS CREEK STATION   TOURISM  OPTUS/TELSTRA -24.40500  131.81700
78                     KULGERA   HIGHWAY  OPTUS/TELSTRA -25.84084  133.30048
84                    LARRIMAH   HIGHWAY          OPTUS -15.57400  133.21500
93        MARY RIVER ROADHOUSE   TOURISM  OPTUS/TELSTRA -13.60500  132.21900
101               MOUNT BUNDEY   HIGHWAY        TELSTRA -12.85500  131.81300
102             MOUNT EBENEZER   TOURISM  OPTUS/TELSTRA -25.17300  132.67400
112           NEWCASTLE WATERS   HIGHWAY        TELSTRA -17.37000  133.40900
121    ORMISTON RANGER STATION   TOURISM          OPTUS -23.63300  132.72800
133   RENNER SPRINGS ROADHOUSE   HIGHWAY          OPTUS -18.31800  133.79500
136          ROSS RIVER RESORT   TOURISM          OPTUS -23.59100  134.49000
140     STUARTS WELL ROADHOUSE   HIGHWAY  OPTUS/TELSTRA -24.33900  133.45800
141        THREEWAYS ROADHOUSE   HIGHWAY          OPTUS -19.43600  134.20800
142    TILMOUTH WELL ROADHOUSE   HIGHWAY        TELSTRA -22.80900  132.59900
144          TIPPERARY STATION   HIGHWAY        TELSTRA -13.73400  131.04100
151      TOP SPRINGS ROADHOUSE   HIGHWAY  OPTUS/TELSTRA -16.54400  131.79600
162   VICTORIA RIVER ROADHOUSE   HIGHWAY          OPTUS -15.61600  131.12700
165               WALKER CREEK   TOURISM          OPTUS -13.12200  130.69500
167                WANGI FALLS   TOURISM          OPTUS -13.15800  130.68400
179              WYCLIFFE WELL   HIGHWAY          OPTUS -20.79500  134.23600
187                     YULARA   TOURISM        TELSTRA -25.24133  130.98766

In [12]:
coverage_cols = [
    "MACRO CELL",
    "SMALL CELL",
    "PROXIMITY TO CELL"
]

df[coverage_cols].notna().sum(axis=1).value_counts()

1    181
2      7
Name: count, dtype: int64

In [13]:
df[df[coverage_cols].isna().all(axis=1)]

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE]
Index: []

In [15]:
df[
    df[coverage_cols].notna().sum(axis=1) == 2
][
    ["SITE NAME", "SITE TYPE", "MACRO CELL",
     "SMALL CELL", "PROXIMITY TO CELL", "PROVIDER"]
]

,SITE NAME,SITE TYPE,MACRO CELL,SMALL CELL,PROXIMITY TO CELL,PROVIDER
17,BARROW CREEK,HIGHWAY,YES,YES,NaN,OPTUS/TELSTRA
32,DALY WATERS,VILLAGE,YES,YES,NaN,OPTUS/TELSTRA
42,ELLIOTT,VILLAGE,YES,YES,NaN,OPTUS/TELSTRA
44,ERLDUNDA,HIGHWAY,YES,YES,NaN,OPTUS/TELSTRA
94,MATARANKA,VILLAGE,YES,YES,NaN,OPTUS/TELSTRA
102,MOUNT EBENEZER,TOURISM,NaN,YES,YES,OPTUS/TELSTRA
108,MUTITJULU,COMMUNITY,YES,NaN,YES,OPTUS/TELSTRA

In [16]:
df["MACRO CELL"].value_counts(dropna=False)

MACRO CELL
NaN    126
YES     62
Name: count, dtype: int64

In [17]:
df["SMALL CELL"].value_counts(dropna=False)

SMALL CELL
NaN    153
YES     35
Name: count, dtype: int64

In [18]:
df["PROXIMITY TO CELL"].value_counts(dropna=False)

PROXIMITY TO CELL
YES    98
NaN    90
Name: count, dtype: int64

In [20]:
df["HAS_MACRO_CELL"] = df["MACRO CELL"].eq("YES")
df["HAS_SMALL_CELL"] = df["SMALL CELL"].eq("YES")
df["HAS_PROXIMITY_CELL"] = df["PROXIMITY TO CELL"].eq("YES")

In [21]:
df[
    [
        "SITE NAME",
        "HAS_MACRO_CELL",
        "HAS_SMALL_CELL",
        "HAS_PROXIMITY_CELL"
    ]
].head()

         SITE NAME  HAS_MACRO_CELL  HAS_SMALL_CELL  HAS_PROXIMITY_CELL
0   ADELAIDE RIVER            True           False               False
1  AILERON STATION           False           False                True
2         ALAMIRRA           False           False                True
3       ALI CURUNG            True           False               False
4     ALPURRURULAM            True           False               False

In [22]:
df["COVERAGE_COUNT"] = (
    df[
        [
            "HAS_MACRO_CELL",
            "HAS_SMALL_CELL",
            "HAS_PROXIMITY_CELL"
        ]
    ]
    .sum(axis=1)
)

In [23]:
df["COVERAGE_COUNT"].value_counts()

COVERAGE_COUNT
1    181
2      7
Name: count, dtype: int64

In [24]:
def get_coverage_type(row):
    types = []

    if row["HAS_MACRO_CELL"]:
        types.append("Macro Cell")

    if row["HAS_SMALL_CELL"]:
        types.append("Small Cell")

    if row["HAS_PROXIMITY_CELL"]:
        types.append("Proximity to Cell")

    return " + ".join(types)


df["COVERAGE_TYPE"] = df.apply(get_coverage_type, axis=1)

In [25]:
df[
    [
        "SITE NAME",
        "COVERAGE_TYPE"
    ]
].head(20)

          SITE NAME            COVERAGE_TYPE
0    ADELAIDE RIVER               Macro Cell
1   AILERON STATION        Proximity to Cell
2          ALAMIRRA        Proximity to Cell
3        ALI CURUNG               Macro Cell
4      ALPURRURULAM               Macro Cell
5         AMOONGUNA        Proximity to Cell
6      AMPILATWATJA               Macro Cell
7         ANGATYEPE        Proximity to Cell
8          ANGURUGU               Macro Cell
9          ARLPARRA               Macro Cell
10         ARMORRAN        Proximity to Cell
11      ARRILLHJERE        Proximity to Cell
12         ATNARARA        Proximity to Cell
13         ATITJERE               Macro Cell
14    AURORA KAKADU        Proximity to Cell
15       BARDALUMBA        Proximity to Cell
16          BARUNGA               Macro Cell
17     BARROW CREEK  Macro Cell + Small Cell
18        BATCHELOR               Macro Cell
19          BELYUEN               Macro Cell

In [26]:
df[
    df["POPULATION"].isna()
][
    [
        "SITE NAME",
        "SITE TYPE",
        "PROVIDER",
        "COVERAGE_TYPE",
        "LATITUDE",
        "LONGITUDE"
    ]
]

,SITE NAME,SITE TYPE,PROVIDER,COVERAGE_TYPE,LATITUDE,LONGITUDE
1,AILERON STATION,HIGHWAY,OPTUS/TELSTRA,Proximity to Cell,-22.50000,133.24500
14,AURORA KAKADU,TOURISM,OPTUS,Proximity to Cell,-12.67600,132.48000
17,BARROW CREEK,HIGHWAY,OPTUS/TELSTRA,Macro Cell + Small Cell,-21.53100,133.88900
29,COOINDA LODGE,TOURISM,TELSTRA,Macro Cell,-12.90500,132.52200
30,CURTAIN SPRINGS ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell,-25.31400,131.75600
32,DALY WATERS,VILLAGE,OPTUS/TELSTRA,Macro Cell + Small Cell,-16.25333,133.36932
33,DEVILS MARBLES HOTEL,TOURISM,OPTUS,Small Cell,-20.64100,134.22300
39,DUNMARRA ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell,-16.67900,133.41200
44,ERLDUNDA,HIGHWAY,OPTUS/TELSTRA,Macro Cell + Small Cell,-25.19700,133.20000
46,FLORENCE FALLS,TOURISM,OPTUS,Small Cell,-13.10900,130.79300
52,GEM TREE PARK,TOURISM,OPTUS,Small Cell,-22.96800,134.24300
53,GLEN HELEN HOMESTEAD,TOURISM,OPTUS,Small Cell,-23.68500,132.67200
75,KINGS CANYON RESORT,TOURISM,OPTUS/TELSTRA,Small Cell,-24.24800,131.51200
76,KINGS CREEK STATION,TOURISM,OPTUS/TELSTRA,Small Cell,-24.40500,131.81700
78,KULGERA,HIGHWAY,OPTUS/TELSTRA,Small Cell,-25.84084,133.30048
84,LARRIMAH,HIGHWAY,OPTUS,Small Cell,-15.57400,133.21500
93,MARY RIVER ROADHOUSE,TOURISM,OPTUS/TELSTRA,Small Cell,-13.60500,132.21900
101,MOUNT BUNDEY,HIGHWAY,TELSTRA,Macro Cell,-12.85500,131.81300
102,MOUNT EBENEZER,TOURISM,OPTUS/TELSTRA,Small Cell + Proximity to Cell,-25.17300,132.67400
112,NEWCASTLE WATERS,HIGHWAY,TELSTRA,Small Cell,-17.37000,133.40900
121,ORMISTON RANGER STATION,TOURISM,OPTUS,Small Cell,-23.63300,132.72800
133,RENNER SPRINGS ROADHOUSE,HIGHWAY,OPTUS,Small Cell,-18.31800,133.79500
136,ROSS RIVER RESORT,TOURISM,OPTUS,Small Cell,-23.59100,134.49000
140,STUARTS WELL ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell,-24.33900,133.45800
141,THREEWAYS ROADHOUSE,HIGHWAY,OPTUS,Small Cell,-19.43600,134.20800
142,TILMOUTH WELL ROADHOUSE,HIGHWAY,TELSTRA,Small Cell,-22.80900,132.59900
144,TIPPERARY STATION,HIGHWAY,TELSTRA,Small Cell,-13.73400,131.04100
151,TOP SPRINGS ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell,-16.54400,131.79600
162,VICTORIA RIVER ROADHOUSE,HIGHWAY,OPTUS,Small Cell,-15.61600,131.12700
165,WALKER CREEK,TOURISM,OPTUS,Macro Cell,-13.12200,130.69500
167,WANGI FALLS,TOURISM,OPTUS,Small Cell,-13.15800,130.68400
179,WYCLIFFE WELL,HIGHWAY,OPTUS,Small Cell,-20.79500,134.23600
187,YULARA,TOURISM,TELSTRA,Macro Cell,-25.24133,130.98766

In [27]:
df["POPULATION"].describe()

count     155.000000
mean      194.580645
std       351.481002
min         5.000000
25%         8.000000
50%        30.000000
75%       242.000000
max      2297.000000
Name: POPULATION, dtype: float64

In [28]:
df["SITE TYPE"].value_counts(dropna=False)

SITE TYPE
COMMUNITY    148
HIGHWAY       17
TOURISM       15
VILLAGE        8
Name: count, dtype: int64

In [29]:
df.groupby("SITE TYPE")["POPULATION"].agg(
    ["count", "mean", "median", "min", "max"]
)

           count        mean  median   min     max
SITE TYPE
COMMUNITY    148  192.385135    25.5   5.0  2297.0
HIGHWAY        0         NaN     NaN   NaN     NaN
TOURISM        0         NaN     NaN   NaN     NaN
VILLAGE        7  241.000000   244.0  49.0   396.0

In [30]:
# Show locations where population is missing
missing_pop = df[df["POPULATION"].isna()]

missing_pop[
    ["SITE NAME", "SITE TYPE", "PROVIDER", "COVERAGE_TYPE"]
]

,SITE NAME,SITE TYPE,PROVIDER,COVERAGE_TYPE
1,AILERON STATION,HIGHWAY,OPTUS/TELSTRA,Proximity to Cell
14,AURORA KAKADU,TOURISM,OPTUS,Proximity to Cell
17,BARROW CREEK,HIGHWAY,OPTUS/TELSTRA,Macro Cell + Small Cell
29,COOINDA LODGE,TOURISM,TELSTRA,Macro Cell
30,CURTAIN SPRINGS ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell
32,DALY WATERS,VILLAGE,OPTUS/TELSTRA,Macro Cell + Small Cell
33,DEVILS MARBLES HOTEL,TOURISM,OPTUS,Small Cell
39,DUNMARRA ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell
44,ERLDUNDA,HIGHWAY,OPTUS/TELSTRA,Macro Cell + Small Cell
46,FLORENCE FALLS,TOURISM,OPTUS,Small Cell
52,GEM TREE PARK,TOURISM,OPTUS,Small Cell
53,GLEN HELEN HOMESTEAD,TOURISM,OPTUS,Small Cell
75,KINGS CANYON RESORT,TOURISM,OPTUS/TELSTRA,Small Cell
76,KINGS CREEK STATION,TOURISM,OPTUS/TELSTRA,Small Cell
78,KULGERA,HIGHWAY,OPTUS/TELSTRA,Small Cell
84,LARRIMAH,HIGHWAY,OPTUS,Small Cell
93,MARY RIVER ROADHOUSE,TOURISM,OPTUS/TELSTRA,Small Cell
101,MOUNT BUNDEY,HIGHWAY,TELSTRA,Macro Cell
102,MOUNT EBENEZER,TOURISM,OPTUS/TELSTRA,Small Cell + Proximity to Cell
112,NEWCASTLE WATERS,HIGHWAY,TELSTRA,Small Cell
121,ORMISTON RANGER STATION,TOURISM,OPTUS,Small Cell
133,RENNER SPRINGS ROADHOUSE,HIGHWAY,OPTUS,Small Cell
136,ROSS RIVER RESORT,TOURISM,OPTUS,Small Cell
140,STUARTS WELL ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell
141,THREEWAYS ROADHOUSE,HIGHWAY,OPTUS,Small Cell
142,TILMOUTH WELL ROADHOUSE,HIGHWAY,TELSTRA,Small Cell
144,TIPPERARY STATION,HIGHWAY,TELSTRA,Small Cell
151,TOP SPRINGS ROADHOUSE,HIGHWAY,OPTUS/TELSTRA,Small Cell
162,VICTORIA RIVER ROADHOUSE,HIGHWAY,OPTUS,Small Cell
165,WALKER CREEK,TOURISM,OPTUS,Macro Cell
167,WANGI FALLS,TOURISM,OPTUS,Small Cell
179,WYCLIFFE WELL,HIGHWAY,OPTUS,Small Cell
187,YULARA,TOURISM,TELSTRA,Macro Cell

In [31]:
missing_pop["SITE TYPE"].value_counts()

SITE TYPE
HIGHWAY    17
TOURISM    15
VILLAGE     1
Name: count, dtype: int64

In [32]:
pop_check = df.groupby("SITE TYPE")["POPULATION"].agg(
    total_rows="size",
    known_population="count"
)

pop_check["missing_population"] = (
    pop_check["total_rows"] - pop_check["known_population"]
)

pop_check["missing_percent"] = (
    pop_check["missing_population"]
    / pop_check["total_rows"]
    * 100
).round(1)

pop_check.sort_values("missing_percent", ascending=False)

           total_rows  known_population  missing_population  missing_percent
SITE TYPE
HIGHWAY            17                 0                  17            100.0
TOURISM            15                 0                  15            100.0
VILLAGE             8                 7                   1             12.5
COMMUNITY         148               148                   0              0.0

In [33]:
df[
    (df["SITE TYPE"] == "VILLAGE") &
    (df["POPULATION"].isna())
][
    ["SITE NAME", "SITE TYPE", "PROVIDER",
     "LATITUDE", "LONGITUDE", "COVERAGE_TYPE"]
]

,SITE NAME,SITE TYPE,PROVIDER,LATITUDE,LONGITUDE,COVERAGE_TYPE
32,DALY WATERS,VILLAGE,OPTUS/TELSTRA,-16.25333,133.36932,Macro Cell + Small Cell

# Population missingness is largely structural:
# - Highway and Tourism sites do not contain population values.
# - All Community sites have population data.
# - One Village has missing population.
# Therefore, missing population values are retained rather than imputed.

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df["SITE NAME"].duplicated().sum()

np.int64(0)

In [36]:
df[df["SITE NAME"].duplicated(keep=False)].sort_values("SITE NAME")

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [37]:
df["SITE TYPE"].value_counts()

SITE TYPE
COMMUNITY    148
HIGHWAY       17
TOURISM       15
VILLAGE        8
Name: count, dtype: int64

In [38]:
df["PROVIDER"].value_counts()

PROVIDER
TELSTRA          134
OPTUS/TELSTRA     40
OPTUS             14
Name: count, dtype: int64

In [39]:
df["SITE TYPE"].unique()

array(['VILLAGE', 'HIGHWAY', 'COMMUNITY', 'TOURISM'], dtype=object)

In [40]:
df["PROVIDER"].unique()

array(['OPTUS/TELSTRA', 'TELSTRA', 'OPTUS'], dtype=object)

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [43]:
df["SITE NAME"].duplicated().sum()

np.int64(0)

In [44]:
df[
    df["SITE NAME"].duplicated(keep=False)
].sort_values("SITE NAME")

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [45]:
df["SITE TYPE"].value_counts()

SITE TYPE
COMMUNITY    148
HIGHWAY       17
TOURISM       15
VILLAGE        8
Name: count, dtype: int64

In [46]:
df["PROVIDER"].value_counts()

PROVIDER
TELSTRA          134
OPTUS/TELSTRA     40
OPTUS             14
Name: count, dtype: int64

In [47]:
df["PROVIDER"].unique()

array(['OPTUS/TELSTRA', 'TELSTRA', 'OPTUS'], dtype=object)

In [48]:
text_cols = [
    "SITE NAME",
    "SITE TYPE",
    "PROVIDER"
]

for col in text_cols:
    df[col] = df[col].str.strip()

In [49]:
df["LATITUDE"].describe()

count    188.000000
mean     -18.346899
std        5.030508
min      -25.840840
25%      -23.744445
50%      -17.499725
75%      -13.149000
max      -11.067000
Name: LATITUDE, dtype: float64

In [50]:
df["LONGITUDE"].describe()

count    188.000000
mean     133.186753
std        1.861881
min      129.010000
25%      131.907545
50%      133.255145
75%      134.238500
max      137.989000
Name: LONGITUDE, dtype: float64

In [51]:
invalid_coords = df[
    ~df["LATITUDE"].between(-44, -10) |
    ~df["LONGITUDE"].between(112, 154)
]

invalid_coords

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [52]:
nt_coord_check = df[
    ~df["LATITUDE"].between(-26, -10) |
    ~df["LONGITUDE"].between(129, 138)
]

nt_coord_check[
    ["SITE NAME", "LATITUDE", "LONGITUDE"]
]

Empty DataFrame
Columns: [SITE NAME, LATITUDE, LONGITUDE]
Index: []

In [53]:
df[
    (df["LATITUDE"] == 0) |
    (df["LONGITUDE"] == 0)
]

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [54]:
df[
    df.duplicated(
        subset=["LATITUDE", "LONGITUDE"],
        keep=False
    )
].sort_values(["LATITUDE", "LONGITUDE"])

Empty DataFrame
Columns: [SITE NAME, SITE TYPE, POPULATION, MACRO CELL, SMALL CELL, PROXIMITY TO CELL, PROVIDER, LATITUDE, LONGITUDE, HAS_MACRO_CELL, HAS_SMALL_CELL, HAS_PROXIMITY_CELL, COVERAGE_COUNT, COVERAGE_TYPE]
Index: []

In [55]:
df.duplicated().sum()
df["SITE NAME"].duplicated().sum()
df["SITE TYPE"].value_counts()
df["PROVIDER"].value_counts()

PROVIDER
TELSTRA          134
OPTUS/TELSTRA     40
OPTUS             14
Name: count, dtype: int64

In [56]:
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate site names:", df["SITE NAME"].duplicated().sum())

print("\nSITE TYPES:")
print(df["SITE TYPE"].value_counts())

print("\nPROVIDERS:")
print(df["PROVIDER"].value_counts())

Exact duplicate rows: 0
Duplicate site names: 0

SITE TYPES:
SITE TYPE
COMMUNITY    148
HIGHWAY       17
TOURISM       15
VILLAGE        8
Name: count, dtype: int64

PROVIDERS:
PROVIDER
TELSTRA          134
OPTUS/TELSTRA     40
OPTUS             14
Name: count, dtype: int64

In [57]:
print("Dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

Dataset shape: (188, 14)

Missing values:
SITE NAME               0
SITE TYPE               0
POPULATION             33
MACRO CELL            126
SMALL CELL            153
PROXIMITY TO CELL      90
PROVIDER                0
LATITUDE                0
LONGITUDE               0
HAS_MACRO_CELL          0
HAS_SMALL_CELL          0
HAS_PROXIMITY_CELL      0
COVERAGE_COUNT          0
COVERAGE_TYPE           0
dtype: int64

Data types:
SITE NAME              object
SITE TYPE              object
POPULATION            float64
MACRO CELL             object
SMALL CELL             object
PROXIMITY TO CELL      object
PROVIDER               object
LATITUDE              float64
LONGITUDE             float64
HAS_MACRO_CELL           bool
HAS_SMALL_CELL           bool
HAS_PROXIMITY_CELL       bool
COVERAGE_COUNT          int64
COVERAGE_TYPE          object
dtype: object

In [58]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [59]:
df.columns

Index(['site_name', 'site_type', 'population', 'macro_cell', 'small_cell',
       'proximity_to_cell', 'provider', 'latitude', 'longitude',
       'has_macro_cell', 'has_small_cell', 'has_proximity_cell',
       'coverage_count', 'coverage_type'],
      dtype='object')

In [60]:
# Save cleaned dataframe as CSV

output_path = r"C:\Users\HP\OneDrive\เอกสาร\remote-connectivity\data\cleaned\nt_mobile_coverage_clean.csv"

df.to_csv(output_path, index=False)

print("File saved successfully!")

File saved successfully!